language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
