baseURL = "https://iky.li"
languageCode = "en-us"
title = "It's Ivan"

canonifyurls  = true
enableEmoji   = true
metaDataFormat = "yaml"

theme = "materialhugo"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "trac"

disqusShortname = "ikyli"
googleAnalytics = "UA-123606967-1"

[markup.goldmark.renderer] 
  unsafe= true

[taxonomies]
  tag = "tags"

[Params]
  mainSections = ["posts", "post"]
  commit = "https://github.com/ivanli/blog/tree/"
  subtitle = "Contains readme, blog, and possibly rants."
  logo = "img/avatar-icon.jpeg"
  favicon = "img/favicon.png"
  dateFormat = "2 January 2006"
  rss = true
  comments = true
  gcse = "017033768780696316302:qal6nttcwac"
  formspree = "ivan@iky.li"

[Author]
  name = "Ivan Li"
  email = "ivan@iky.li"
  facebook = "ivankyli"
  github = "ivanli"
  stackoverflow = "ivankyli"
  instagram = "ivanky.li"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

# F5F9F8, 97A5AB, EE3F3F, A96E52, 302D30
# F1F0EF, 6DC2DC, 0C9FE6, 5A6A87, 19304E
# F6F6F5, AC96A4, E47D4D, D04358, 2D364B
