baseURL = "https://iky.li"
languageCode = "en-us"
title = "IKY.LI - It's Ivan"

canonifyurls  = true
enableEmoji   = true
metaDataFormat = "yaml"

theme = "beautifulhugo"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "trac"

disqusShortname = "ikyli"
googleAnalytics = "UA-123606967-1"

[taxonomies]
  tag = "tags"

[Params]
  commit = "https://github.com/ivanli/blog/tree/"
  subtitle = "Contains readme, blog, and possibly rants."
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.png"
  dateFormat = "2 January 2006"
  rss = true
  comments = true
  gcse = "011435975563082698690:ozu4jqu-x80"

[Author]
  name = "Ivan Li"
  email = "ivan@iky.li"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2
