baseURL = "http://ivanli.github.io/blog"
languageCode = "en-us"
title = "IKY.LI - Ivan's Blog"

canonifyurls  = true
enableEmoji   = true
metaDataFormat = "yaml"

theme = "beautifulhugo"

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "trac"

#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[taxonomies]
  tag = "tags"

[Params]
  commit = "https://github.com/ivanli/blog/tree/"
  subtitle = "readme, blog, and possibly rants."
  logo = "img/avatar-icon.png"
  favicon = "favicon.ico"
  dateFormat = "2 January 2006"
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Ivan Li"
  email = "ivankyli@gmail.com"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2
